In [1]:
import pandas as pd

In [2]:
df= pd.read_csv(r'C:\Users\Pedro\Documents\GitHub\analise-criminalidade-rj\data\raw\BaseDPEvolucaoMensalCisp.csv', encoding= 'latin1', sep= ';', dtype='str')

In [17]:
df

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2,0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3,0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10,0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3,0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0,0,3,0,0,0,0,0,57,2

In [44]:
df_limpo = df.melt(id_vars= ["mes", "ano", "munic", "regiao"],
        var_name= "tipo_crime",
        value_vars= ['hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
                     'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
                     'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
                     'hom_culposo', 'lesao_corp_culposa','total_roubos', 'total_furtos', 'registro_ocorrencias'],
        value_name= "quantidade")

In [45]:
df_limpo['quantidade']= df_limpo['quantidade'].fillna(0).astype('int')

In [46]:
df_limpo.columns

Index(['mes', 'ano', 'munic', 'regiao', 'tipo_crime', 'quantidade'], dtype='object')

In [47]:
df_limpo['mes'] =df_limpo['ano']  + '_' + '0' +  df_limpo['mes']
df_limpo.rename(columns={'mes':'Mes_Ano'}, inplace= True)
df_limpo.drop(columns= 'ano', inplace= True)

In [50]:
df_limpo

        Mes_Ano           munic    regiao             tipo_crime  quantidade
0       2003_01  Angra dos Reis  Interior                   cvli           7
1       2003_01  Angra dos Reis  Interior                estupro           4
2       2003_01  Angra dos Reis  Interior            feminicidio           0
3       2003_01  Angra dos Reis  Interior            hom_culposo           3
4       2003_01  Angra dos Reis  Interior             hom_doloso           7
...         ...             ...       ...                    ...         ...
357467  2026_01   Volta Redonda  Interior   registro_ocorrencias        1366
357468  2026_01   Volta Redonda  Interior             tentat_hom           2
357469  2026_01   Volta Redonda  Interior  tentativa_feminicidio           2
357470  2026_01   Volta Redonda  Interior           total_furtos         153
357471  2026_01   Volta Redonda  Interior           total_roubos          10

[357472 rows x 5 columns]

In [49]:
df_limpo = df_limpo.groupby(by= ['Mes_Ano', 'munic', 'regiao', 'tipo_crime'], as_index= False).sum()